In [2]:
import numpy as np

In [3]:
# Collect data
x = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])

y = np.array([[0],[1],[1],[0]])


In [6]:
print(x)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [7]:
print(y)

[[0]
 [1]
 [1]
 [0]]


In [9]:
# Build model

num_epochs = 60000

# initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1


In [10]:
print(syn0)

[[ 0.36195641  0.49785417  0.52240968 -0.01084409]
 [-0.19860129 -0.32528769  0.97120163 -0.10503215]
 [ 0.06965537  0.48934007  0.97831064 -0.85381898]]


In [11]:
print(syn1)

[[ 0.62615193]
 [ 0.43275859]
 [ 0.12675182]
 [ 0.02515294]]


In [13]:
def nonlin(x, deriv = False):
    if(deriv == True):
        return x*(1-x)
    
    return 1/(1 + np.exp(-x))

In [25]:
# Step 3 Train Model
for j in range(num_epochs):
    # feed forward through layer 0,1 and 2
    l0 = x
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    
    # how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))
    
    # in what direction is the target value?
    l2_delta = l2_error*nonlin(l2, deriv = True)
    
    # How much did each l2 value contribute to l2 error
    l1_error = l2_delta.dot(syn1.T)
    
    l1_delta = l1_error*nonlin(l1, deriv = True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Error:0.00416073660064
Error:0.00383638470168
Error:0.00357674281469
Error:0.00336288847581
Error:0.00318282419742
Error:0.0030285297378
