In [4]:
import tensorflow as tf

In [5]:
a = tf.placeholder(tf.float32)

In [6]:
b = a * 2

k = [1, 2, 3]

In [8]:
with tf.Session() as sess:
    result = sess.run(b, feed_dict = {a:k})
    print(result)

[ 2.  4.  6.]


In [7]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print(result)

[[[  2.   4.   6.]
  [  8.  10.  12.]
  [ 14.  16.  18.]
  [ 20.  22.  24.]]

 [[ 26.  28.  30.]
  [ 32.  34.  36.]
  [ 38.  40.  42.]
  [ 44.  46.  48.]]]
