In [14]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

iris = load_iris()
test_idx = [0,50,100]

In [15]:
# training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

In [16]:
# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

In [17]:
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [18]:
print(test_target)

[0 1 2]


In [19]:
print(clf.predict(test_data))

[0 1 2]


In [29]:
with open("iris.dot", 'w') as f:
...     f = tree.export_graphviz(clf, out_file=f)

import os
os.unlink('iris.dot')

In [30]:
>>> import pydotplus 
>>> dot_data = tree.export_graphviz(clf, out_file=None) 
>>> graph = pydotplus.graph_from_dot_data(dot_data) 
>>> graph.write_pdf("iris.pdf") 

ImportError: No module named 'pydotplus'

In [31]:
>>> from IPython.display import Image  
>>> dot_data = tree.export_graphviz(clf, out_file=None, 
                         feature_names=iris.feature_names,  
                         class_names=iris.target_names,  
                         filled=True, rounded=True,  
                         special_characters=True)  
>>> graph = pydotplus.graph_from_dot_data(dot_data)  
>>> Image(graph.create_png())  

AttributeError: 'NoneType' object has no attribute 'write'

In [32]:
print(test_data[1], test_target[1])

[ 7.   3.2  4.7  1.4] 1


In [36]:
print(iris.feature_names, iris.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] ['setosa' 'versicolor' 'virginica']
