In [1]:
import pandas as pd
import random
import numpy as np
import matplotlib
% matplotlib inline

In [2]:
df = pd.read_json('../data/sampledf.json')
df.index = ["R{:02d}".format(i) for i in range(len(df))]
df.columns = ["C{:02d}".format(i) for i in range(len(df.columns))]
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09
R00   79   19   21   99   35   59   44   25   75   58
R01   25   39   89   66    9   41    6   69   63    3
R02   37   64   31   69   61   97    5   11   76   57
R03   74   61  100    6   58   80   95   50   15   51
R04   79   60   83   85   16    5   16   69    5   20
R05   45   26   73   73  100   60   21   19   95   12
R06   12   29   18   98   62   68   92   29   74   96
R07   36   32   22    4   66   25   63   51   59   14
R08   55   53   89   13   84   87   74    3    2   64
R09   46   74   36   54   21   12   68   33   80   25

### Adding and deleting Series in a DataFrame

In [3]:
df['C10'] = [random.randint(1, 100) for i in range(len(df))]
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   41
R01   25   39   89   66    9   41    6   69   63    3   43
R02   37   64   31   69   61   97    5   11   76   57    9
R03   74   61  100    6   58   80   95   50   15   51   89
R04   79   60   83   85   16    5   16   69    5   20   33
R05   45   26   73   73  100   60   21   19   95   12   62
R06   12   29   18   98   62   68   92   29   74   96   95
R07   36   32   22    4   66   25   63   51   59   14   87
R08   55   53   89   13   84   87   74    3    2   64   18
R09   46   74   36   54   21   12   68   33   80   25   21

In [4]:
# caveat when adding a Series:
new_series = pd.Series(list([random.randint(1, 100) for i in range(len(df))]))

In [5]:
df['C10'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58  NaN
R01   25   39   89   66    9   41    6   69   63    3  NaN
R02   37   64   31   69   61   97    5   11   76   57  NaN
R03   74   61  100    6   58   80   95   50   15   51  NaN
R04   79   60   83   85   16    5   16   69    5   20  NaN
R05   45   26   73   73  100   60   21   19   95   12  NaN
R06   12   29   18   98   62   68   92   29   74   96  NaN
R07   36   32   22    4   66   25   63   51   59   14  NaN
R08   55   53   89   13   84   87   74    3    2   64  NaN
R09   46   74   36   54   21   12   68   33   80   25  NaN

In [6]:
# adding a new Series: mind the index of the the DF
new_series.index = df.index
df['C10'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58    6
R01   25   39   89   66    9   41    6   69   63    3   34
R02   37   64   31   69   61   97    5   11   76   57   56
R03   74   61  100    6   58   80   95   50   15   51   31
R04   79   60   83   85   16    5   16   69    5   20   83
R05   45   26   73   73  100   60   21   19   95   12   22
R06   12   29   18   98   62   68   92   29   74   96   34
R07   36   32   22    4   66   25   63   51   59   14   21
R08   55   53   89   13   84   87   74    3    2   64   67
R09   46   74   36   54   21   12   68   33   80   25   80

In [7]:
df['C11'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10  C11
R00   79   19   21   99   35   59   44   25   75   58    6    6
R01   25   39   89   66    9   41    6   69   63    3   34   34
R02   37   64   31   69   61   97    5   11   76   57   56   56
R03   74   61  100    6   58   80   95   50   15   51   31   31
R04   79   60   83   85   16    5   16   69    5   20   83   83
R05   45   26   73   73  100   60   21   19   95   12   22   22
R06   12   29   18   98   62   68   92   29   74   96   34   34
R07   36   32   22    4   66   25   63   51   59   14   21   21
R08   55   53   89   13   84   87   74    3    2   64   67   67
R09   46   74   36   54   21   12   68   33   80   25   80   80

In [8]:
del df['C11']
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58    6
R01   25   39   89   66    9   41    6   69   63    3   34
R02   37   64   31   69   61   97    5   11   76   57   56
R03   74   61  100    6   58   80   95   50   15   51   31
R04   79   60   83   85   16    5   16   69    5   20   83
R05   45   26   73   73  100   60   21   19   95   12   22
R06   12   29   18   98   62   68   92   29   74   96   34
R07   36   32   22    4   66   25   63   51   59   14   21
R08   55   53   89   13   84   87   74    3    2   64   67
R09   46   74   36   54   21   12   68   33   80   25   80

In [9]:
del df['C12']

KeyError: 'C12'

In [10]:
# avoid KeyErrors if unsure Series exists
df.drop(['C12'], errors='ignore')

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58    6
R01   25   39   89   66    9   41    6   69   63    3   34
R02   37   64   31   69   61   97    5   11   76   57   56
R03   74   61  100    6   58   80   95   50   15   51   31
R04   79   60   83   85   16    5   16   69    5   20   83
R05   45   26   73   73  100   60   21   19   95   12   22
R06   12   29   18   98   62   68   92   29   74   96   34
R07   36   32   22    4   66   25   63   51   59   14   21
R08   55   53   89   13   84   87   74    3    2   64   67
R09   46   74   36   54   21   12   68   33   80   25   80

In [11]:
# getting a subset is simpler than delting many columns
dfs = df.loc[:, ['C03', 'C05']]
dfs

C03  C05
R00   99   59
R01   66   41
R02   69   97
R03    6   80
R04   85    5
R05   73   60
R06   98   68
R07    4   25
R08   13   87
R09   54   12

### Mangle your data

**recall: NumPy Broadcasting**

In [12]:
a = np.random.rand(3,1)
a

array([[ 0.69438018],
       [ 0.49186634],
       [ 0.068667  ]])

In [13]:
b = np.random.rand(3,1)
b

array([[ 0.76775455],
       [ 0.10113759],
       [ 0.83192903]])

In [14]:
a + b

array([[ 1.46213473],
       [ 0.59300393],
       [ 0.90059602]])

In [15]:
a - b

array([[-0.07337438],
       [ 0.39072875],
       [-0.76326203]])

In [16]:
a * b

array([[ 0.53311354],
       [ 0.04974618],
       [ 0.05712607]])

In [17]:
a / b

array([[ 0.9044299 ],
       [ 4.86333854],
       [ 0.08253949]])

In [18]:
a + 7

array([[ 7.69438018],
       [ 7.49186634],
       [ 7.068667  ]])

In [19]:
b // 2

array([[ 0.],
       [ 0.],
       [ 0.]])

In [20]:
a % 2 == 0

array([[False],
       [False],
       [False]], dtype=bool)

In [21]:
a * [4, 5]

array([[ 2.7775207 ,  3.47190088],
       [ 1.96746537,  2.45933171],
       [ 0.27466799,  0.34333498]])

### Pandas

In [22]:
sales_data = pd.read_json('../data/blooth_sales_data.json',
                              convert_dates=['birthday', 'orderdate']
                              )
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units  
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2  
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41  
3 2016-07-23 13:48:03.156638             iPhone     584.01     16  
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4

In [23]:
sales_data['turnover'] = sales_data['unitprice'] * sales_data['units']
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units   turnover  
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2      26.54  
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  635925.94  
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41     647.39  
3 2016-07-23 13:48:03.156638             iPhone     584.01     16    9344.16  
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4     102.76

In [28]:
sales_data['turnover'].mean()

57794.30212

In [29]:
sales_data.mean()

unitprice     2202.87399
units           25.84200
turnover     57794.30212
dtype: float64

In [30]:
sales_data['turnover'].median()

560.3799999999999

In [31]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 8 columns):
birthday     1000 non-null datetime64[ns]
customer     1000 non-null object
name         1000 non-null object
orderdate    1000 non-null datetime64[ns]
product      1000 non-null object
unitprice    1000 non-null float64
units        1000 non-null int64
turnover     1000 non-null float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(3)
memory usage: 70.3+ KB


In [32]:
# map for Series
sales_data['year'] = sales_data['orderdate'].map(lambda x: x.year)
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units   turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2      26.54   
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  635925.94   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41     647.39   
3 2016-07-23 13:48:03.156638             iPhone     584.01     16    9344.16   
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4     102.76   

   year  
0  2016  
1  2016  
2  2016  
3  2016  
4  2016

In [33]:
# map for Series
sales_data['month'] = sales_data['orderdate'].map(lambda x: x.month)
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units   turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2      26.54   
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  635925.94   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41     647.39   
3 2016-07-23 13:48:03.156638             iPhone     584.01     16    9344.16   
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4     102.76   

   year  month  
0  2016      7  
1  2016      7  
2  2016      7  
3  2016      7  
4  2016      7

In [34]:
# combine multiple columns
sales_data['year-month'] = sales_data['year'].map(
    str) + sales_data['month'].map(lambda x: "-{:02d}".format(x))

In [35]:
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units   turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2      26.54   
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  635925.94   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41     647.39   
3 2016-07-23 13:48:03.156638             iPhone     584.01     16    9344.16   
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4     102.76   

   year  month year-month  
0  2016      7    2016-07  
1  2016      7    2016-07  
2  2016      7    2016-07  
3  2016      7    2016-07  
4  2016      7    2016-07

In [36]:
# applymap for df
sales_data[['unitprice', 'units']].applymap(lambda x: x / 1.5).head(5)

unitprice      units
0      8.846667   1.333333
1  16305.793333  17.333333
2     10.526667  27.333333
3    389.340000  10.666667
4     17.126667   2.666667

In [37]:
# remember: a copy of the DF is returned. The DF is not altered.
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units   turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2      26.54   
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  635925.94   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41     647.39   
3 2016-07-23 13:48:03.156638             iPhone     584.01     16    9344.16   
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4     102.76   

   year  month year-month  
0  2016      7    2016-07  
1  2016      7    2016-07  
2  2016      7    2016-07  
3  2016      7    2016-07  
4  2016      7    2016-07

In [38]:
sales_data['unitprice'] = sales_data['unitprice'].map(lambda x: x * 2)

In [39]:
sales_data.describe()

unitprice        units      turnover    year       month
count   1000.000000  1000.000000  1.000000e+03  1000.0  1000.00000
mean    4405.747980    25.842000  5.779430e+04  2016.0     6.96600
std    12739.726665    14.581689  1.948077e+05     0.0     0.18132
min       10.040000     1.000000  1.000000e+01  2016.0     6.00000
25%       21.550000    13.000000  2.600000e+02  2016.0     7.00000
50%       36.010000    26.000000  5.603800e+02  2016.0     7.00000
75%     1017.960000    39.000000  9.991180e+03  2016.0     7.00000
max    49934.620000    50.000000  1.206765e+06  2016.0     7.00000

In [40]:
sales_data['birthday'].describe()

count                    1000
unique                    284
top       1986-11-05 00:00:00
freq                       10
first     1951-10-15 00:00:00
last      1998-12-29 00:00:00
Name: birthday, dtype: object

In [41]:
sales_data['turnover'] = sales_data['turnover'].astype(np.int)
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units  turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      26.54      2        26   
1 2016-07-06 13:48:03.156596            Corolla   48917.38     26    635925   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      31.58     41       647   
3 2016-07-23 13:48:03.156638             iPhone    1168.02     16      9344   
4 2016-07-16 13:48:03.156657  Harry Potter book      51.38      4       102   

   year  month year-month  
0  2016      7    2016-07  
1  2016      7    2016-07  
2  2016      7    2016-07  
3  2016      7    2016-07  
4  2016      7    2016-07

In [42]:
# sneak in NaN
sales_data.set_value(1, 'unitprice', np.NaN)
sales_data.set_value(4, 'unitprice', np.NaN)
sales_data.set_value(3, 'orderdate', np.NaN)
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units  turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      26.54      2        26   
1 2016-07-06 13:48:03.156596            Corolla        NaN     26    635925   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      31.58     41       647   
3                        NaT             iPhone    1168.02     16      9344   
4 2016-07-16 13:48:03.156657  Harry Potter book        NaN      4       102   

   year  month year-month  
0  2016      7    2016-07  
1  2016      7    2016-07  
2  2016      7    2016-07  
3  2016      7    2016-07  
4  2016      7    2016-07

In [43]:
sales_data[sales_data['unitprice'].isnull()]

birthday                    customer   name                  orderdate  \
1 1968-12-13  Electronics Resource Group  India 2016-07-06 13:48:03.156596   
4 1972-04-23       Star Alpha Industries  Chang 2016-07-16 13:48:03.156657   

             product  unitprice  units  turnover  year  month year-month  
1            Corolla        NaN     26    635925  2016      7    2016-07  
4  Harry Potter book        NaN      4       102  2016      7    2016-07

In [44]:
sales_data.dropna().head(5)

birthday                           customer      name  \
0 1967-09-02                    Electronics Inc  Pasquale   
2 1992-09-10      East Application Contract Inc     Wayne   
5 1953-03-17             Network Application Co    Weldon   
6 1977-10-23  Omega Pacific Future Incorporated      Sung   
7 1982-07-02              Medicine Incorporated     Emily   

                   orderdate          product  unitprice  units  turnover  \
0 2016-07-17 13:48:03.156566  Thriller record      26.54      2        26   
2 2016-07-22 13:48:03.156618     Rubik’s Cube      31.58     41       647   
5 2016-07-22 13:48:03.156678          Lipitor      22.44      1        11   
6 2016-07-09 13:48:03.156698      PlayStation     589.80     25      7372   
7 2016-07-16 13:48:03.156717  Thriller record      36.54      5        91   

   year  month year-month  
0  2016      7    2016-07  
2  2016      7    2016-07  
5  2016      7    2016-07  
6  2016      7    2016-07  
7  2016      7    2016-07

In [45]:
sales_data.fillna(99.99).head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                      orderdate            product  unitprice  units  \
0 2016-07-17 13:48:03.156566000    Thriller record      26.54      2   
1 2016-07-06 13:48:03.156596000            Corolla      99.99     26   
2 2016-07-22 13:48:03.156618000       Rubik’s Cube      31.58     41   
3 1970-01-01 00:00:00.000000099             iPhone    1168.02     16   
4 2016-07-16 13:48:03.156657000  Harry Potter book      99.99      4   

   turnover  year  month year-month  
0        26  2016      7    2016-07  
1    635925  2016      7    2016-07  
2       647  2016      7    2016-07  
3      9344  2016      7    2016-07  
4       102  2016      7    2016-07

In [46]:
sales_data.head()

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units  turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      26.54      2        26   
1 2016-07-06 13:48:03.156596            Corolla        NaN     26    635925   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      31.58     41       647   
3                        NaT             iPhone    1168.02     16      9344   
4 2016-07-16 13:48:03.156657  Harry Potter book        NaN      4       102   

   year  month year-month  
0  2016      7    2016-07  
1  2016      7    2016-07  
2  2016      7    2016-07  
3  2016      7    2016-07  
4  2016      7    2016-07

In [47]:
sales_data.fillna(99.99, inplace=True)
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                      orderdate            product  unitprice  units  \
0 2016-07-17 13:48:03.156566000    Thriller record      26.54      2   
1 2016-07-06 13:48:03.156596000            Corolla      99.99     26   
2 2016-07-22 13:48:03.156618000       Rubik’s Cube      31.58     41   
3 1970-01-01 00:00:00.000000099             iPhone    1168.02     16   
4 2016-07-16 13:48:03.156657000  Harry Potter book      99.99      4   

   turnover  year  month year-month  
0        26  2016      7    2016-07  
1    635925  2016      7    2016-07  
2       647  2016      7    2016-07  
3      9344  2016      7    2016-07  
4       102  2016      7    2016-07